// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/api/cocktail/[id].ts";
import * as $1 from "./routes/api/random-cocktails.ts";
import * as $2 from "./routes/api/search.ts";
import * as $3 from "./routes/drink/[id].tsx";
import * as $4 from "./routes/index.tsx";
import * as $$0 from "./islands/Counter.tsx";
import * as $$1 from "./islands/SearchInput.tsx";

const manifest = {
  routes: {
    "./routes/api/cocktail/[id].ts": $0,
    "./routes/api/random-cocktails.ts": $1,
    "./routes/api/search.ts": $2,
    "./routes/drink/[id].tsx": $3,
    "./routes/index.tsx": $4,
  },
  islands: {
    "./islands/Counter.tsx": $$0,
    "./islands/SearchInput.tsx": $$1,
  },
  baseUrl: import.meta.url,
};

export default manifest;
